/*
 * Mooncord, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2026 Vendicated and Vesktop contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "./patches/blockDiscordAppPrompt";
import "./patches/tabActivity";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import SettingsUi from "./components/settings/Settings";
import { MooncordSettingsIcon } from "./components/SettingsIcon";
import { MooncordLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

MooncordLogger.log("read if cute :3");
MooncordLogger.log("Mooncord v" + MooncordNative.app.getVersion());

const SettingsPlugin = Vencord.Plugins.plugins
    .Settings as typeof import("@vencord/types/plugins/_core/settings").default;

SettingsPlugin.customEntries.push({
    key: "mooncord",
    title: "Mooncord",
    panelTitle: "Mooncord Settings",
    Component: SettingsUi,
    Icon: MooncordSettingsIcon
});
